name: Update README with latest results

on:
  push:
    branches: [ master, main ]
    paths:
      - 'results/**'
  pull_request:
    types: [ closed ]
    branches: [ master, main ]

permissions:
  contents: write

jobs:
  update-readme:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Update README
      run: make readme
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code README.md || echo "changed=true" >> $GITHUB_OUTPUT
    
    - name: Commit and push if changed
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Auto-update README.md with latest test results [skip ci]"
        git push